#language: generic 
sudo: required
services:
   - docker

before_install:
   - docker build -t rishabh/docker-react -f Dockerfile.dev .
    
script:
   - docker run -e CI=true rishabh/docker-react npm run test
